### ISSUE TITLE
required providers source path for child modules needs to reflect new path

### ISSUE THREAD

**Issue by christophercorn** [oracle-terraform-modules/terraform-oci-logging#15]
# Description
terraform init returns:
```
│ Warning: Additional provider information from registry
│ 
│ The remote registry returned warnings for registry.terraform.io/hashicorp/oci:
│ - For users on Terraform 0.13 or greater, this provider has moved to oracle/oci. Please update your source in required_providers.
```

this is because the child modules cannot inherit "source = oracle/oci" from the parent module. inheritance does not work here. as documented here:
https://developer.hashicorp.com/terraform/language/modules/develop/providers

> Note: Only provider configurations are inherited by child modules, not provider source or version requirements. Each module must [declare its own provider requirements](https://developer.hashicorp.com/terraform/language/providers/requirements). This is especially important for non-HashiCorp providers.

**Comment by karthicgit** [comment]
fixed.
